# Generated by Django 5.2.6 on 2025-09-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peca', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('prateleira', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
                ('minimo', models.IntegerField()),
            ],
        ),
    ]
