# Generated by Django 5.2.6 on 2025-09-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fabricante',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
    ]
